### ISSUE TITLE
icinga2-selinux does not install sebool CentOS 7

### ISSUE THREAD

**Issue by bengelberth-shadowsoft** [Icinga/icinga-packaging#130] opened 2019-02-28 15:19 UTC
icinga2-selinux-2.10.3-1.el7.icinga.x86_64 does not install the required sebool if an older version of selinux-policy-targeted-3.13.1-192.el7_5.3.noarch is installed.  It silently fails and installs the rpm successfully.

Expected output:
```
[root@icinga-master1-sgsk-default ~]# getsebool -a|grep icinga
httpd_can_connect_icinga2_api --> on
httpd_can_write_icinga2_command --> on
icinga2_can_connect_all --> off
icinga2adm_exec_content --> on
```
Actual output:
```
[root@icinga-master0-sgsk-default ~]# getsebool -a|grep icinga
[root@icinga-master0-sgsk-default ~]# 
```

It seems the problem is with the dependency of policycoreutils-python: https://github.com/Icinga/rpm-icinga2/blob/master/icinga2.spec#L267

I think it needs a minimum version associated with it now.

Before upgrading selinux-policy-targeted the system had:
```
policycoreutils-2.5-22.el7.x86_64
policycoreutils-python-2.5-22.el7.x86_64
```
and the sebool did not get installed.

After upgrading selinux-policy-targeted the system had:
```
policycoreutils-2.5-29.el7_6.1.x86_64
policycoreutils-python-2.5-29.el7_6.1.x86_64
```
and the sebool did get installed.

**Comment by dgoetz** [comment] 2019-02-28 15:49
I had a look into the problem and on my systems (CentOS 7) `setsebool` was always installed as part of `policycoreutils`.

Also it is not required by the package as no scriptlet is using the command. For the scriptlets we use `semanage` which is moved to `policycoreutils-python-utils` in Fedora and RHEL 8 what is already addressed in the spec.

If for some reason `setsebool`/`getsebool` is not available, you can use also `semanage boolean` to getting or setting SELinux booleans.

So I do not see a general problem here, but can you verify if it is somehow reproduceable on your systems? If you find one with 2.5-22 and `setsebool`/`getsebool` missing, can you run `rpm -qV policycoreutils` which will tell you `missing     /usr/sbin/setsebool` if the binary was deleted after it was installed by the package? In such case a reinstall or upgrade of the package would reinstall the binary.

**Comment by bengelberth-shadowsoft** [comment] 2019-02-28 16:03
It is not that the binary setsebool or getsebool are missing.

It is that on 2.5-22 the se boolean attributes are not available to set on or off: httpd_can_connect_icinga2_api, httpd_can_write_icinga2_command, icinga2_can_connect_all, icinga2adm_exec_content

I am not an selinux expert but I think it is because the following loop is failing silently on every iteration with 2.5.-22 policycoreutils installed.  https://github.com/Icinga/rpm-icinga2/blob/master/icinga2.spec#L601

So, if this is the case a minimum version requirement could be set for the policycoreutils dependencies.  Then policycoreutils and policycoreutils-python-utils get upgraded as a dependency when icinga2-selinux is installed, if it is on an older version?

Thank you for taking a look at this.

**Comment by dgoetz** [comment] 2019-02-28 16:41
@bengelberth-shadowsoft: It is not policycoreutils which causes the problem, it is the policy itself. We probably create the package always with the latest version and it looks like there was a backwards incompatible change which lets the SELinux module installation fail (found the same problem for other policies like container-selinux while doing research). This is the reason why the booleans are not available.

@lazyfrosch: While I am not strictly against a dependency on the policy but it was a breakage in the same version of the policy only release was increased, changelog is not telling anything about a possible break and it manifests only if Icinga 2 is upgraded but not the underlaying os, so I fear we would add a dependency including the release which a typically try to avoid for complexity. Also we can not avoid this in the future and should add this as a test case to the test environment. Something like having the latest 2 minor releases without updates and install/upgrade Icinga 2 and perhaps the other way (only upgrading the os and not Icinga 2), too. If some problem occurs we can at least add this to the upgrade notes. Whats your opinion?

**Comment by widhalmt** [comment] 2019-03-01 15:39
ref/IC/12221

**Comment by lazyfrosch** [comment] 2019-03-04 13:23
I think those issues should be pretty rare.

Usually RedHat would automatically update selinux tools when Icinga 2 is updated (due to updating dependencies). This can be blocked with snapshots of the upstream repository, so if Icinga 2 updates are available, but RedHat are locked to a certain state.

I'm against introducing a new dependency here.

@dgoetz is this likely to happen again?

**Comment by dgoetz** [comment] 2019-03-04 19:09
No breaking changes should not happen at all within a release and from the other issues I found it sounded like an error with branching.

**Comment by lazyfrosch** [comment] 2019-04-26 12:23
I guess we can close this...

**Closed by lazyfrosch** 2019-04-26 12:23 UTC
