### ISSUE TITLE
Centos Requirements - PHP 7.3 EOL

### ISSUE THREAD

**Issue by FooBarTrixibell** [Icinga/icinga-packaging#285] opened 2023-04-25 20:35 UTC
Packages for Icingaweb have requirements for EOL PHP 7.3 packages

error: Failed dependencies:
        /opt/rh/rh-php73/root/usr/bin/php is needed by icingacli-2.11.1-1.el7.icinga.noarch
        rh-php73-php-cli >= 7.2 is needed by icingacli-2.11.1-1.el7.icinga.noarch
        rh-php73-php-gettext is needed by icinga-php-library-0.11.1-1.el7.noarch
        rh-php73-php-intl is needed by icinga-php-library-0.11.1-1.el7.noarch
        rh-php73-php-json is needed by icinga-php-library-0.11.1-1.el7.noarch
        rh-php73-php-openssl is needed by icinga-php-library-0.11.1-1.el7.noarch
        rh-php73-php-pdo is needed by icinga-php-library-0.11.1-1.el7.noarch
        rh-php73-php-curl is needed by icinga-php-thirdparty-0.11.0-1.el7.icinga.noarch
        rh-php73-php-soap is needed by icinga-php-thirdparty-0.11.0-1.el7.icinga.noarch
        rh-php73-php-sockets is needed by icinga-php-thirdparty-0.11.0-1.el7.icinga.noarch
        icingacli = 2.11.4-2.el7 is needed by icingaweb2-2.11.4-2.el7.noarch
        icingaweb2-common = 2.11.4-2.el7 is needed by icingaweb2-2.11.4-2.el7.noarch
        php-icinga = 2.11.4-2.el7 is needed by icingaweb2-2.11.4-2.el7.noarch
        icingaweb2 = 2.11.1-1.el7.icinga is needed by icingaweb2-selinux-2.11.1-1.el7.icinga.noarch
        rh-php73-php-common >= 7.2 is needed by icingaweb2-vendor-dompdf-2.11.1-1.el7.icinga.noarch
        rh-php73-php-common >= 7.2 is needed by icingaweb2-vendor-HTMLPurifier-1:2.11.1-1.el7.icinga.noarch
        rh-php73-php-common >= 7.2 is needed by icingaweb2-vendor-JShrink-2.11.1-1.el7.icinga.noarch
        rh-php73-php-common >= 7.2 is needed by icingaweb2-vendor-lessphp-2.11.1-1.el7.icinga.noarch
        rh-php73-php-common >= 7.2 is needed by icingaweb2-vendor-Parsedown-2.11.1-1.el7.icinga.noarch
        rh-php73-php-common >= 7.2 is needed by icingaweb2-vendor-zf1-2.11.1-1.el7.icinga.noarch
        rh-php73-php-common >= 7.2 is needed by php-Icinga-2.11.1-1.el7.icinga.noarch
        rh-php73-php-gd is needed by php-Icinga-2.11.1-1.el7.icinga.noarch
        rh-php73-php-intl is needed by php-Icinga-2.11.1-1.el7.icinga.noarch
        rh-php73-php-mbstring is needed by php-Icinga-2.11.1-1.el7.icinga.noarch
        rh-php73-php-pdo is needed by php-Icinga-2.11.1-1.el7.icinga.noarch
        rh-php73-php-xml is needed by php-Icinga-2.11.1-1.el7.icinga.noarch

If you install php 8.1 from remi (I haven't tried 8.2 yet) -
`yum install https://rpms.remirepo.net/enterprise/remi-release-7.rpm`
Enable the php 8.1 repo and then install the actual php requirements -
`yum install php-gd php-gmp php-fpm php-pdo php-cli php-mbstring php-ldap php-mysqlnd php-soap gd3php php-xml php-pecl-imagick php-process php-common oniguruma5php php-intl`
and then download the RPM packages -
```
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/icingaweb2-2.11.4-2.el7.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/icingaweb2-common-2.11.1-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/icingaweb2-selinux-2.11.1-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/icingaweb2-vendor-HTMLPurifier-2.11.1-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/icingaweb2-vendor-JShrink-2.11.1-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/icingaweb2-vendor-Parsedown-2.11.1-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/php-Icinga-2.11.1-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/icingaweb2-vendor-zf1-2.11.1-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/icingaweb2-vendor-lessphp-2.11.1-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/icingaweb2-vendor-dompdf-2.11.1-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icingaweb2/icingacli-2.11.1-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icinga-php-thirdparty/icinga-php-thirdparty-0.11.0-1.el7.icinga.noarch.rpm
wget https://packages.icinga.com/centos/7Server/release/noarch/icinga-php-library/icinga-php-library-0.11.1-1.el7.noarch.rpm
```
And install them with --nodeps -
`rpm -Uvh *.rpm --nodeps`

Then as far as I can tell icingaweb2 works fine. I have seen a lot of git issues in the actual icingaweb2 repo on PHP 8.2 compatibility so I think that work is all done, just the old requirements are still in the RPM spec.

**Comment by FooBarTrixibell** [comment] 2023-04-26 19:52
Icingacli has the same requirement but also needs modified to work with 8.

wget https://packages.icinga.com/centos/7Server/release/noarch/icingacli/icingacli-2.11.4-2.el7.noarch.rpm
rpm -Uvh icingacli-2.11.4-2.el7.noarch.rpm --nodeps
vim /usr/bin/icingacli

Modify the top line to point to /usr/bin/php

**Comment by Al2Klimov** [comment] 2024-06-12 13:47
Duplicate of #235

**Closed as completed** 2024-06-21 09:43 UTC
