### ISSUE TITLE
packages.icinga.com key is rejected

### ISSUE THREAD

**Issue by scolardc** [Icinga/icinga-packaging#306] opened 2024-06-24 01:31 UTC
https://packages.icinga.com/icinga.key untrusted public key algorithm: dsa1024

Err:6 https://packages.icinga.com/ubuntu icinga-noble InRelease
  The following signatures were invalid: F51A91A5EE001AA5D77D53C4C6E319C334410682 (untrusted public key algorithm: dsa1024)
Reading package lists... Done
W: GPG error: https://packages.icinga.com/ubuntu icinga-noble InRelease: The following signatures were invalid: F51A91A5EE001AA5D77D53C4C6E319C334410682 (untrusted public key algorithm: dsa1024)
E: The repository 'https://packages.icinga.com/ubuntu icinga-noble InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by Al2Klimov** [comment] 2024-06-26 11:19
Duplicate of #91

**Comment by Al2Klimov** [comment] 2024-06-26 11:23
Hello and thank you for reporting!

Please share your `/etc/apt/sources.list.d/noble-icinga.list`.

Best,
A/K

**Comment by ranirahn** [comment] 2024-08-01 10:04
The issue was know for months(if not years) now and for me its still only on warning stages, but when will the key be changed already? Maybe the best way would be to make icinga-keyring package like someone suggested and rotate the new keys out. At some point all distros disable dsa1024 and then what? This should have been done years ago for my opinion.

**Comment by Al2Klimov** [comment] 2024-08-05 12:52
> Maybe the best way would be to make icinga-keyring package like someone suggested and rotate the new keys out.

@bobapple How does our schedule look like?

**Comment by bobapple** [comment] 2024-08-27 06:41
Key will be update on September 30, 2024

https://icinga.com/blog/2024/08/26/icinga-package-repository-key-rotation-2024/

**Closed as completed by bobapple** 2024-08-27 06:41 UTC
