### ISSUE TITLE
No php 7.4 for Centos7

### ISSUE THREAD

**Issue by inf0rmix** [Icinga/icinga-packaging#211] opened 2021-07-08 07:59 UTC
Hi,

I have a Centos7 installation with rh-php73 .

I have search for php74 upgrades and they are not available. Is there any plan to support remi php 7.4 apache module ?

As far as I remember from upgrade last year, there is a dependency inside the rpm package for icingaweb2 which makes it impossible to install it with mod_php.

Is there any way to get it running with php 7.4 on Centos7 ?

**Comment by htriem** [comment] 2021-09-08 16:03
I'd have to test this, but the most likely route will be us increasing the php version as a whole, which might happen next year.

**Comment by Al2Klimov** [comment] 2024-06-17 14:27
Duplicate of #235

**Closed** 2024-06-25 13:43 UTC
Labels: os/epel, package/icingaweb2
