### ISSUE TITLE
IcingaDB redis service in docs

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/icinga-packaging#282] opened 2023-03-02 09:28 UTC
In the documentation of Icingadb-redis under debian you are advised to start the service `icingadb-redis`. However, this service does not exist under debian. There it can be found under `icingadb-redis-server`

Failure while starting `icingadb-redis`:
`Failed to enable unit: Too many levels of symbolic links`

On Ubuntu the service `icingadb-redis` also only points to `icingadb-redis-server`.
```
$ systemctl status icingadb-redis
● icingadb-redis-server.service - Advanced key-value store
...
```

## To Reproduce

* Install icingadb-redis on Debian
* try `systemctl enable --now icingadb-redis`

## Expected behavior

The service should be named on all distros the same.

**Comment by tbauriedel** [comment] 2023-03-02 09:28
ref/NC/778073

**Comment by tbauriedel** [comment] 2023-05-02 09:37
Any progress on this topic?

**Comment by oxzi** [comment] 2024-03-22 09:11
FYI, there is <https://github.com/Icinga/icinga2/pull/9877> adjusting the documentation.

**Comment by Al2Klimov** [comment] 2024-06-26 11:34
Duplicate of https://github.com/Icinga/icinga2/issues/9511

**Closed as completed** 2024-06-26 11:40 UTC
