### ISSUE TITLE
SCL: Bump PHP version (7.3 is EOL soon)

### ISSUE THREAD

**Issue by Linuxfabrik** [Icinga/icinga-packaging#226] opened 2021-10-28 14:55 UTC
PHP 7.3 is end of life on 6 Dec 2021.

See https://github.com/Icinga/icinga-packaging/issues/182

**Comment by Al2Klimov** [comment] 2024-06-12 13:42
Duplicate of #235

**Closed** 2024-07-01 09:50 UTC
Labels: package/icingaweb2
