### ISSUE TITLE
php version icingacli and web are different

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icinga-packaging#298] opened 2024-01-24 16:31 UTC
## Describe the bug
I have upgraded from php version 7.3.33 to 8.1.27.
After the upgrade I see that the web version is 8.1.27
but the version via icingacli is still 7.3.33

## To Reproduce
yum upgrade version from 7.3.33 to 8.1.27 en check de version on the web and via icingacli

## Expected behavior
That the version via icingacli is the same as the one via the web

## Screenshots

![icingacli_20240124](https://github.com/Icinga/icingadb-web/assets/29303758/eaccae66-65d0-443a-bee5-04f7a583ff5b)

![icingaweb_20240124](https://github.com/Icinga/icingadb-web/assets/29303758/dcbd8817-5a16-492c-a9b4-0406aaa5b4d3)

## Version PHP
# php -v
```
PHP 8.1.27 (cli) (built: Dec 19 2023 20:35:55) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.27, Copyright (c), by Zend Technologies
```

# yum list
`php81-php.x86_64                      8.1.27-1.el7.remi
`

# systemctl -a | grep php
`php81-php-fpm.service     loaded    active   running   The PHP FastCGI Process Manager`

# Linux 
# cat /etc/redhat-release
`Red Hat Enterprise Linux Server release 7.9 (Maipo)`

# uname -a
`Linux xxxxx 3.10.0-1160.92.1.el7.x86_64`

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

icingaweb2.noarch                     2.12.1+0.gcd2daeb2c-1702677855.el7                                                                      
icingaweb2-common.noarch              2.12.1+0.gcd2daeb2c-1702677855.el7                                                                       
php-icinga.noarch                     2.12.1+0.gcd2daeb2c-1702677855.el7                                                                       
icingacli.noarch                      2.12.1+0.gcd2daeb2c-1702677855.el7                                                                       
icingadb-web.noarch                   1.1.1+0.g274b903c-1702681473.el7 

icinga2.x86_64                        2.14.2-1.el7                     
icinga2-bin.x86_64                    2.14.2-1.el7                     
icinga2-common.x86_64                 2.14.2-1.el7                     
icinga2-ido-pgsql.x86_64              2.14.2-1.el7                     
vim-icinga2.x86_64                    2.14.2-1.el7                     
icingadb.x86_64                       1.1.1+13.g0e9810c-1702677846.el7 

icingadb-redis.x86_64                 7.0.12-1.el7                     
icingadb-redis-debuginfo.x86_64       7.0.12-1.el7                     
icingadb-redis-devel.x86_64           7.0.12-1.el7                     

icinga-l10n.noarch                    1.3.0+6.g7ae9998f-1702674230.el7 
icinga-php-common.noarch              1.0.0165655404400000000-0.20220630.0154.el7.icinga
icinga-php-library.noarch             0.13.1+4.g7d54fbd-1702674329.el7 
icinga-php-thirdparty.noarch          0.12.1+3.g2eeed31-1702674368.el7

**Comment by gbin2265** [comment] 2024-01-28 22:08
Now I understand why my bug was placed under icinga-packaging.

icinga-cli still needs php 7.3 under rhel 7.

If I want to remove the version of php 7.3, it also removes icingaweb2, icingadb-web and icingacli.

yum erase rh-php73*

Removing:
 rh-php73-php-cli                      x86_64                 7.3.33-1.el7
 rh-php73-php-common                   x86_64                 7.3.33-1.el7
 rh-php73-php-fpm                      x86_64                 7.3.33-1.el7
 rh-php73-php-gd                       x86_64                 7.3.33-1.el7
 rh-php73-php-gmp                      x86_64                 7.3.33-1.el7
 rh-php73-php-intl                     x86_64                 7.3.33-1.el7
 rh-php73-php-json                     x86_64                 7.3.33-1.el7
 rh-php73-php-ldap                     x86_64                 7.3.33-1.el7
 rh-php73-php-mbstring                 x86_64                 7.3.33-1.el7
 rh-php73-php-mysqlnd                  x86_64                 7.3.33-1.el7
 rh-php73-php-pdo                      x86_64                 7.3.33-1.el7
 rh-php73-php-pgsql                    x86_64                 7.3.33-1.el7
 rh-php73-php-process                  x86_64                 7.3.33-1.el7
 rh-php73-php-soap                     x86_64                 7.3.33-1.el7
 rh-php73-php-xml                      x86_64                 7.3.33-1.el7
 rh-php73-php-zip                      x86_64                 7.3.33-1.el7
 rh-php73-runtime                      x86_64                 1-1.el7     
 
Removing for dependencies:
 icinga-cube                           noarch                 1.3.2+0.g10192ca-1706310237.el7   
 icinga-cube-web                       noarch                 1.3.2+0.g10192ca-1706310237.el7   
 icinga-php-library                    noarch                 0.13.1+4.gdc6c896-1706303262.el7  
 icinga-php-thirdparty                 noarch                 0.12.1+3.g085f5e9-1706303316.el7  
 icingacli                             noarch                 2.12.1+0.gcd2daeb2c-1706309247.el7
 icingadb-web                          noarch                 1.1.1+0.g274b903c-1706310231.el7  
 icingaweb2                            noarch                 2.12.1+0.gcd2daeb2c-1706309247.el7
 php-icinga                            noarch                 2.12.1+0.gcd2daeb2c-1706309247.el7

**Comment by Al2Klimov** [comment] 2024-06-17 14:28
Duplicate of #235

**Closed as completed** 2024-07-01 10:25 UTC
