### ISSUE TITLE
Updating Icinga2 on raspberry pi 3

### ISSUE THREAD

**Issue by ClaudiaBuehler** [Icinga/icinga-packaging#45] opened 2017-09-22 12:13 UTC
When doing "sudo apt-get update" I get the follwing message:

"Hit:1 http://packages.icinga.com/debian icinga-stretch InRelease
Hit:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Hit:3 http://archive.raspberrypi.org/debian stretch InRelease
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://packages.icinga.com/debian icinga-stretch InRelease' doesn't support architecture 'armhf'"

Could you please help me.

**Comment by dnsmichi** [comment] 2017-09-22 12:35
Duplicate of #20.

**Closed by dnsmichi** 2017-09-22 12:35 UTC
