### ISSUE TITLE
No armv7hl packages under epel

### ISSUE THREAD

**Issue by FrostbyteGR** [Icinga/icinga-packaging#131] opened 2019-04-11 19:05 UTC
Hello,

I've noticed that you guys resolved the package building for armhf and raspbian earlier this year.

However, I want to use the [official CentOS](https://wiki.centos.org/SpecialInterestGroup/AltArch/Arm32/RaspberryPi3) 7.6 image with my Raspberry Pi 3.
I'm not keen on using Raspbian or Ubuntu for my purposes. I could use [Debian Buster](https://wiki.debian.org/RaspberryPi3), but it's still in it's "EXPERIMENTAL" phase.

[root@rpi3 ~]# dnf install icinga2
ICINGA (stable release for epel)     1.0 MB/s | 442 kB     00:00
CentOS Kernels for armhfp           0.0  B/s |   0  B     00:00
Last metadata expiration check: 0:00:02 ago on Thu 11 Apr 2019 09:42:30 PM EEST.
Error:
 Problem: conflicting requests
  - package icinga2-2.10.0-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.10.0-1.el7.icinga needed by icinga2-2.10.0-1.el7.icinga.x86_64
  - nothing provides icinga2-common = 2.10.0-1.el7.icinga needed by icinga2-2.10.0-1.el7.icinga.x86_64
  - package icinga2-2.10.1-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-common = 2.10.1-1.el7.icinga needed by icinga2-2.10.1-1.el7.icinga.x86_64
  - nothing provides icinga2-bin = 2.10.1-1.el7.icinga needed by icinga2-2.10.1-1.el7.icinga.x86_64
  - package icinga2-2.10.2-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-common = 2.10.2-1.el7.icinga needed by icinga2-2.10.2-1.el7.icinga.x86_64
  - nothing provides icinga2-bin = 2.10.2-1.el7.icinga needed by icinga2-2.10.2-1.el7.icinga.x86_64
  - package icinga2-2.10.3-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-common = 2.10.3-1.el7.icinga needed by icinga2-2.10.3-1.el7.icinga.x86_64
  - nothing provides icinga2-bin = 2.10.3-1.el7.icinga needed by icinga2-2.10.3-1.el7.icinga.x86_64
  - package icinga2-2.10.4-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-common = 2.10.4-1.el7.icinga needed by icinga2-2.10.4-1.el7.icinga.x86_64
  - nothing provides icinga2-bin = 2.10.4-1.el7.icinga needed by icinga2-2.10.4-1.el7.icinga.x86_64
  - package icinga2-2.4.10-1.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.4.10-1.el7.centos needed by icinga2-2.4.10-1.el7.centos.x86_64
  - package icinga2-2.5.0-1.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.5.0-1.el7.centos needed by icinga2-2.5.0-1.el7.centos.x86_64
  - package icinga2-2.5.0-2.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.5.0-2.el7.centos needed by icinga2-2.5.0-2.el7.centos.x86_64
  - package icinga2-2.5.0-3.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.5.0-3.el7.centos needed by icinga2-2.5.0-3.el7.centos.x86_64
  - package icinga2-2.5.1-1.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.5.1-1.el7.centos needed by icinga2-2.5.1-1.el7.centos.x86_64
  - package icinga2-2.5.2-1.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.5.2-1.el7.centos needed by icinga2-2.5.2-1.el7.centos.x86_64
  - package icinga2-2.5.3-1.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.5.3-1.el7.centos needed by icinga2-2.5.3-1.el7.centos.x86_64
  - package icinga2-2.5.4-1.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.5.4-1.el7.centos needed by icinga2-2.5.4-1.el7.centos.x86_64
  - package icinga2-2.6.0-1.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.6.0-1.el7.centos needed by icinga2-2.6.0-1.el7.centos.x86_64
  - package icinga2-2.6.1-1.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.6.1-1.el7.centos needed by icinga2-2.6.1-1.el7.centos.x86_64
  - package icinga2-2.6.2-1.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.6.2-1.el7.centos needed by icinga2-2.6.2-1.el7.centos.x86_64
  - package icinga2-2.6.3-1.el7.centos.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.6.3-1.el7.centos needed by icinga2-2.6.3-1.el7.centos.x86_64
  - package icinga2-2.7.0-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.7.0-1.el7.icinga needed by icinga2-2.7.0-1.el7.icinga.x86_64
  - package icinga2-2.7.1-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.7.1-1.el7.icinga needed by icinga2-2.7.1-1.el7.icinga.x86_64
  - package icinga2-2.7.2-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.7.2-1.el7.icinga needed by icinga2-2.7.2-1.el7.icinga.x86_64
  - package icinga2-2.8.0-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.8.0-1.el7.icinga needed by icinga2-2.8.0-1.el7.icinga.x86_64
  - package icinga2-2.8.1-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.8.1-1.el7.icinga needed by icinga2-2.8.1-1.el7.icinga.x86_64
  - package icinga2-2.8.2-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.8.2-1.el7.icinga needed by icinga2-2.8.2-1.el7.icinga.x86_64
  - package icinga2-2.8.3-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.8.3-1.el7.icinga needed by icinga2-2.8.3-1.el7.icinga.x86_64
  - package icinga2-2.8.4-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.8.4-1.el7.icinga needed by icinga2-2.8.4-1.el7.icinga.x86_64
  - package icinga2-2.9.0-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.9.0-1.el7.icinga needed by icinga2-2.9.0-1.el7.icinga.x86_64
  - package icinga2-2.9.1-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.9.1-1.el7.icinga needed by icinga2-2.9.1-1.el7.icinga.x86_64
  - package icinga2-2.9.2-1.el7.icinga.x86_64 does not have a compatible architecture
  - nothing provides icinga2-bin = 2.9.2-1.el7.icinga needed by icinga2-2.9.2-1.el7.icinga.x86_64

Possible to throw some love my way?
In the event that it's not feasible, please provide instructions on how to create the required RPMs from source. (Bonus points if cross-compile instructions are included)

Thank you!

**Comment by dnsmichi** [comment] 2019-04-12 07:20
Currently there's no plans to support anything else than Raspbian. This was a customer sponsored project with many community requests for PI based embedded hardware. As you probably have seen, there's still gcc regressions and compiler problems on ARM based architectures, so up until those are not resolved, I don't think it is a good idea to look into other distributions either. 

Building a package isn't the only task we need to do, what if there's bugs on specific platforms, where the developers need to debug and look into. That's a direction where we don't have resources nor knowledge for. Even Raspbian already is a challenge, when you fix a line of code and wait 30 minutes for compilation.

Rebuilding packages from RPM should be possible by using the SRPM with rpmbuild, There's many howtos on the internet, here's one from [CentOS](https://wiki.centos.org/HowTos/RebuildSRPM). In terms of cross building, I have no knowledge but certainly upstream should provide such guides. [This one](https://dmitry.khlebnikov.net/2016/05/raspberry-pi-3-toolchain-on-centos-7.html) looks like it would need lots of hacks. However, if you run into architecture specific problems there's little chance that someone will be able to help you.

If I were you, I would use Raspbian and meet everyone else in the community when you have questions. 

Cheers,
Michael

**Comment by FrostbyteGR** [comment] 2019-04-12 07:48
Thank you for the information.

I understand where you're coming from, in fact, I did expect this very answer.
May I suggest, however, that you guys tackle this [how CentOS handled the Epel repository for Raspberri Pi](https://wiki.centos.org/SpecialInterestGroup/AltArch/armhfp#head-2c416cfaecdf675f43a5be7a81ad50e81e640c93); as an automatic rebuild without any signing/QA/test/support, just for the sake of convenience.

I will attempt to set up a x64_86 CentOS VM for cross-compiling purposes and see where this gets me.
If I manage to achieve a straightforward solution, may I share it with you so you guys can at least offer the resulting packages in your repository? Again, without any support, just delivered as-is.

Cheers,
John

**Comment by FrostbyteGR** [comment] 2019-04-12 11:48
It ended up being too difficult to produce an RPM package for armv7hl after all..

mock will not help, as it doesn't support cross compiling.
Building a VM with nested QEMU and emulate the CentOS armv7hl image is a nightmare.
So I wrote the mock method off..

rpmbuild won't do us any good without a proper SPEC file either.
I'm not that experienced as to write one on my own; so, wrote that method off too..

Searching for Icinga2 2.10.4 armv7hl packages yielded some results, but the only available packages are from SuSE Leap.
Since these packages are intended for a different distribution, with different requirements and dependencies, this method had to be written off too..

I have given up on trying to build an RPM package.
Currently building and installing it from source, it's gonna take a while.

If anything does change in the future and you start providing armv7hl RPMs for Epel, let me know.

Thank you!

Cheers,
John

**Comment by FrostbyteGR** [comment] 2019-04-26 13:29
Hello,

I wanted to chime in and have a little bit of a do-over on my last response.
Here are my findings so far:
1) I do recall that there was a way under debian/ubuntu to install packages/libraries from other architectures and then cross build the package in a chroot environment. I haven't discovered how to do this on RHEL/CentOS/Fedora yet, or if it's even possible to do so at all.

2) Cross compiling/building for armv7hl doesn't seem to be feasible at this point; at least not with a x64_86 VM.
Even if you attempt nested virtualization, QEMU will greet you with the following:
`ERROR    unsupported configuration: qemu-xhci not supported in this QEMU binary`
A little bit of digging through the mailing lists also confirms it..
> Short answer: No, you cannot run virtual ARM using KVM on physical x86.

3) So I decided to go for the least effective method, native building..
Now, on a previous (deleted) response I did a mistake when reviewing the SPEC file, thinking that I wouldn't be able to build on anything else bar x86_64/i386. After a careful re-read, I realized that what I was reading there, were just some conditions that applied **if** the target was x86_64/i386.
So after doing a small test drive with SRPMs obtained through [your repo](https://packages.icinga.com/epel/7/release/src/), I decided to move things over inside a docker container for two reasons:
I. It's an isolated environment, which I can also clean up easily if I so desire.
II. When I get to finish building my RPi cluster (docker swarm) in the future, I will be able to just throw a container at one (idling) of it's nodes and have it do my bidding without disrupting any other running nodes/services.

This is what I have done so far:
`# Create a 3GB swapfile to prevent an OOM situation during the rebuild
dd if=/dev/zero of=/swapfile bs=1024 count=3145728
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile

# Spin up a docker container from the CentOS image
docker pull centos
docker run --name icinga2-builder -it centos

# Prepare the build environment within the container
cat <<'EOF' > /etc/yum.repos.d/CentOS-armhfp-epel.repo
[epel]
name=Epel rebuild for armhfp
baseurl=https://armv7.dev.centos.org/repodir/epel-pass-1/
enabled=1
gpgcheck=0

EOF
yum install -y deltarpm
yum upgrade -y
curl -O https://packages.icinga.com/epel/7/release/src/icinga2-2.10.4-1.el7.icinga.src.rpm
yum-builddep -y icinga2-*.rpm
yum install -y yajl-devel ccache rpm-build
ln -s /bin/ccache /usr/local/bin/gcc
ln -s /bin/ccache /usr/local/bin/g++

# Build the RPM
rpmbuild --rebuild icinga2-*.rpm

###################################
# This is going to take a while!
###################################
# To detach: CTRL-P + CTRL-Q
# To reattach: 'docker attach icinga2-builder'
###################################

# Compress the final RPMs and clean up
cd ~/rpmbuild/RPMS/armv7hl && tar -czvf ~/icinga2-2.10.4-1.el7.icinga.armv7hl.tar.gz *.armv7hl.rpm
cd ~ && rm -rf ~/rpmbuild
rm -f /icinga2-2.10.4-1.el7.icinga.src.rpm

# Return to the host
exit

# Copy the package from the container to the host
docker cp icinga2-builder:/root/icinga2-2.10.4-1.el7.icinga.armv7hl.tar.gz ~/

# Clean up the swapfile
swapoff /swapfile
rm -f /swapfile`

If I do discover an easier/faster way, I will let you know. But for now, this will do the trick.

Thanks!

**Comment by lazyfrosch** [comment] 2019-04-26 13:36
We are already building Raspbian inside Docker with qemu-user-static.

I'm not sure about a possible user base for CentOS, or other RPM based distributions on ARM.

Raspbian was realized because of a concrete use case and a big community using Raspbian on Raspberry Pi.

We can basically build anything, but someone has to test and support it...

**Comment by FrostbyteGR** [comment] 2019-04-26 15:23
But is there really much of a difference between an RPM and DEB based ARM distributions, when it comes to compiling, packaging and how your code interacts/behaves within the OS?

I know how and can handle equally both types of aforementioned distributions. But as time goes by, I find myself ever so increasingly attracted towards the "parent" distributions that others have been based upon (hence why I mentioned pure Debian/CentOS in the original post). I find their minimal offerings to be the perfect starting point, whether you are dealing with a very limited platform (such as an single board computer) or just basically want to shape a machine with only the necessities and nothing excess.

On RHEL/CentOS specifically now, the more and more I kept on using them.. the more I was convinced that they are actually a tad stabler (and slimmer) than their DEB counterparts.
And since I was made aware that they've picked up the Raspberry Pi and started maintaining an official image.. well, it was a no-brainer.

Onto the subject of community and testers, well.. [Grafana does it](https://grafana.com/grafana/download?platform=arm), so why shouldn't you too?
It's better to at least have something, than nothing at all; even if it's untested in it's infancy.
Pretty sure that there will be testers, if something to test with exists.

I know I might be awfully pedantic about this.. but I'd **love to** at least have that option.

Cheers.

**Comment by lazyfrosch** [comment] 2019-04-27 07:25
I'm not it will work, but it takes work and time.

And later still effort to keep it running.

**Comment by dnsmichi** [comment] 2019-04-29 06:56
@FrostbyteGR true, everything is possible. If you consider that Icinga and all its projects, modules, infrastructure, support, community, etc. is run by roughly ~20 people, you'll likely better understand that this is a matter of resources, knowledge (transfer) and time.

Anyhow, as you've already seen, cross building on CentOS/Fedora isn't that well documented nor supported than with Raspbian. If that changes and someone comes up with a working script and infrastructure, we may reconsider. The very same happened with the long standing Raspbian request where community members stood up and shared everything required - well, and a gentle customer sponsoring the last missing days to finally do it. 

https://github.com/Icinga/icinga-packaging/issues/20#issuecomment-405226342

Building the source code has been documented quite extensively in the past years, and everything else which is needed to cope with the code, not only using the packages. Start here: https://icinga.com/docs/icinga2/snapshot/doc/21-development/#develop-icinga-2

Cheers,
Michael

**Comment by FrostbyteGR** [comment] 2019-04-29 11:30
@dnsmichi Fair point.
Until there's a way, may I have permission to offer (unofficial) natively-built packages on my git?

Also quick confirmation, @lazyfrosch said that unity builds are disabled in packaging based on target architecture. But when I rebuilt for armv7hl I think I did catch a few unity related things with my eye, plus the build took 7 hours to complete.

Is there a way to pass -ICINGA2_UNITY_BUILD=OFF when "rpmbuild --rebuild" calls cmake?
Or is this something that you guys can fix in the spec file?

Thanks,
John

**Comment by lazyfrosch** [comment] 2019-04-29 12:49
Yes you need to update the spec file with a rule like you suggested. :+1: 

Building directly on ARM is a problem since the CPUs are pretty slow. We are actually building in a virtualized Docker image for Raspbian. This reduces build times a lot, but is not easy to explain.

ccache is very robust will only use cached files if the environment matches. E.g. if you update gcc, ccache will ignore its cache.

**Comment by FrostbyteGR** [comment] 2019-04-29 12:59
Any chance we can get `--with` and `--without` conditional build statements at some point, for the RPM packaging branch? I can do it just fine with the spec file rule, but I would prefer this much cleaner method.
I'm pretty sure this would make the x64_86 CentOS Docker/VM user-base happy as well.

Actually the RAM (not enough) and the I/O (swapfile) are biggest problems, I believe.
CPU could be better, but it's far from being the worst offender in this setup, in my opinion.

Gotcha, then I will just issue a `ccache -C` and start from scratch.

**Comment by dnsmichi** [comment] 2019-04-29 13:01
> But, until there's a way, may I have permission to offer (unofficial) natively-built packages on my git?

Sure, open source is all about sharing and caring. Speaking of Raspbian, @nbuchwitz shared his packages on their host too. Users should be aware that this isn't official, and you should know how to tackle support questions (if you have issues opened up). The rest is more or less ensuring it works for both sides, with subtle patches and knowledge transfer :)

**Comment by FrostbyteGR** [comment] 2019-04-29 21:38
I've been talking it over with the maintainers of the official CentOS 7.6 image on IRC.
They are offering to build (on their aarch64 farm) and host it as long as there are SRPMs available on your end.

I know that you're maintaining your own repository, but can we get permission/guidelines to have unofficial packages in their [EPEL repo](https://wiki.centos.org/SpecialInterestGroup/AltArch/armhfp?action=show&redirect=SpecialInterestGroup%2FAltArch%2FArm32#head-2c416cfaecdf675f43a5be7a81ad50e81e640c93)?

If yes, we will need a way to set `ICINGA2_UNITY_BUILD` to `OFF` without extracting the SRPM and modifying the SPEC file, so they can pump it directly (possibly with the help of some arguments) to their farm.

Thanks!

**Comment by lazyfrosch** [comment] 2019-04-30 08:25
Anyone can rebuild our packages, just don't call them officially (supported) by Icinga.

We currently have a pretty custom build environment, but this is due to other requirements on how to build (e.g. snapshots from GIT), and also various distributions.

If a group of users is interested in Icinga packages for CentOS arm, we will think about it. But not just because of one user, sorry...

Contributions to our SPEC file is always welcome, it is hosted under [rpm-icinga2](https://github.com/Icinga/rpm-icinga2)

**Comment by FrostbyteGR** [comment] 2019-04-30 11:44
[There you go](https://github.com/Icinga/rpm-icinga2/pull/12).

It's all good, if in the future there's more interest, I will be looking forward to it!
Thank you for putting up with me and for your time so far. :)

**Comment by htriem** [comment] 2021-09-09 09:08
Closed as a duplicate, we'll continue the discussion in #220.

**Closed by htriem** 2021-09-09 09:08 UTC
Labels: os/epel, arch/arm64
