### ISSUE TITLE
Package is missing from distribution ... looking to reinstall icinga2 on an arm-based device

### ISSUE THREAD

**Issue by grmhay** [Icinga/icinga-packaging#22] opened 2017-07-02 03:20 UTC
icinga2-ido-mysql_2.6.3-1~debmon8+1_armhf.deb

**Comment by lazyfrosch** [comment] 2017-07-21 13:13
See #20

**Comment by lazyfrosch** [comment] 2017-07-21 13:14
duplicate of #20

**Closed by lazyfrosch** 2017-07-21 13:13 UTC
